#ifndef _MA_VERSION_H_
#define _MA_VERSION_H_

#define MA_MAJOR_VERSION  1
#define MA_MINOR_VERSION  0
#define MA_PATCH_VERSION  0

#define MA_AT_API_VERSION "v0"

#define __MA_VERSION__    MA_MAJOR_VERSION "." MA_MINOR_VERSION "." MA_PATCH_VERSION


#endif
